-- MySQL Script generated by MySQL Workbench
-- 02/03/18 22:50:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dcstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dcstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dcstore` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `dcstore` ;

-- -----------------------------------------------------
-- Table `dcstore`.`article_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`article_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`user_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(70) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`user` (
  `id` VARCHAR(20) NOT NULL,
  `name` VARCHAR(70) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `last_name` VARCHAR(70) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `type` INT UNSIGNED NOT NULL,
  `remember_token` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `user_user_type_idx` (`type` ASC),
  CONSTRAINT `user_user_type`
    FOREIGN KEY (`type`)
    REFERENCES `dcstore`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`article` (
  `id` VARCHAR(30) NOT NULL,
  `type` INT UNSIGNED NOT NULL,
  `created_by` VARCHAR(20) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `article_article_type_idx` (`type` ASC),
  INDEX `article_user_idx` (`created_by` ASC),
  INDEX `article_user_2_idx` (`updated_by` ASC),
  CONSTRAINT `article_article_type`
    FOREIGN KEY (`type`)
    REFERENCES `dcstore`.`article_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `article_user`
    FOREIGN KEY (`created_by`)
    REFERENCES `dcstore`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `article_user_2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `dcstore`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`quality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`quality` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`format` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `format` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`lenguage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`lenguage` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lenguage` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`subtitles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`subtitles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subtitles` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`information` (
  `id` VARCHAR(30) NOT NULL,
  `quality` INT UNSIGNED NOT NULL,
  `format` INT UNSIGNED NOT NULL,
  `resolution_w` INT UNSIGNED NOT NULL,
  `resolution_h` INT UNSIGNED NOT NULL,
  `size` INT UNSIGNED NOT NULL,
  `lenguage` INT UNSIGNED NOT NULL,
  `subtitles` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `information_quality_quality_movie_idx` (`quality` ASC),
  INDEX `information_quality_format_movie_idx` (`format` ASC),
  INDEX `information_quality_lenguage_movie_idx` (`lenguage` ASC),
  INDEX `information_quality_subtitles_movie_idx` (`subtitles` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `information_quality`
    FOREIGN KEY (`quality`)
    REFERENCES `dcstore`.`quality` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `information_format`
    FOREIGN KEY (`format`)
    REFERENCES `dcstore`.`format` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `information_lenguage`
    FOREIGN KEY (`lenguage`)
    REFERENCES `dcstore`.`lenguage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `information_subtitles`
    FOREIGN KEY (`subtitles`)
    REFERENCES `dcstore`.`subtitles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `information_article`
    FOREIGN KEY (`id`)
    REFERENCES `dcstore`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`country` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`datasheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`datasheet` (
  `id` VARCHAR(30) NOT NULL,
  `original_title` VARCHAR(70) NOT NULL,
  `another _title` VARCHAR(70) NOT NULL,
  `year` INT NOT NULL,
  `duration` INT NOT NULL,
  `country` INT UNSIGNED NOT NULL,
  `directed` VARCHAR(70) NOT NULL,
  `screenplay` VARCHAR(70) NOT NULL,
  `music` VARCHAR(70) NOT NULL,
  `cinematography` VARCHAR(70) NOT NULL,
  `starring` VARCHAR(250) NOT NULL,
  `production_company` VARCHAR(100) NOT NULL,
  `genders` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `datasheet_country_idx` (`country` ASC),
  CONSTRAINT `datasheet_country`
    FOREIGN KEY (`country`)
    REFERENCES `dcstore`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `datasheet_information`
    FOREIGN KEY (`id`)
    REFERENCES `dcstore`.`information` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`gender` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`genders` (
  `id` VARCHAR(30) NOT NULL,
  `gender` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `genders_gender_idx` (`gender` ASC),
  CONSTRAINT `genders_gender`
    FOREIGN KEY (`gender`)
    REFERENCES `dcstore`.`gender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `gender_datasheet`
    FOREIGN KEY (`id`)
    REFERENCES `dcstore`.`datasheet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`photo` (
  `id` VARCHAR(30) NOT NULL,
  `photo` VARCHAR(512) NOT NULL,
  INDEX `photo_movie_idx` (`id` ASC),
  CONSTRAINT `photo_movie`
    FOREIGN KEY (`id`)
    REFERENCES `dcstore`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`information_software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`information_software` (
  `id` VARCHAR(30) NOT NULL,
  `title` VARCHAR(70) NOT NULL,
  `lenguage` INT UNSIGNED NOT NULL,
  `size` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `information_software_lenguage_idx` (`lenguage` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `information_software_lenguage`
    FOREIGN KEY (`lenguage`)
    REFERENCES `dcstore`.`lenguage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `information_software_article`
    FOREIGN KEY (`id`)
    REFERENCES `dcstore`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`feature_software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`feature_software` (
  `id` VARCHAR(30) NOT NULL,
  `feature` VARCHAR(1024) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `feature_software_information_software`
    FOREIGN KEY (`id`)
    REFERENCES `dcstore`.`information_software` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`format_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`format_game` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `format` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`plataform_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`plataform_game` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `plataform` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`gender_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`gender_game` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`information_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`information_game` (
  `id` VARCHAR(30) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `release_date` DATETIME NOT NULL,
  `format` INT UNSIGNED NOT NULL,
  `plataform` INT UNSIGNED NOT NULL,
  `size` INT UNSIGNED NOT NULL,
  `lenguaje` INT UNSIGNED NOT NULL,
  `gender` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `information_software_plataform_game_idx` (`plataform` ASC),
  INDEX `information_software__gender_game_idx` (`gender` ASC),
  INDEX `information_software_format_game_idx` (`format` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `information_game_format_game`
    FOREIGN KEY (`format`)
    REFERENCES `dcstore`.`format_game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `information_game_plataform_game`
    FOREIGN KEY (`plataform`)
    REFERENCES `dcstore`.`plataform_game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `information_game__gender_game`
    FOREIGN KEY (`gender`)
    REFERENCES `dcstore`.`gender_game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `information_game_article`
    FOREIGN KEY (`id`)
    REFERENCES `dcstore`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`os` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `os` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`requirements_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`requirements_game` (
  `id` VARCHAR(30) NOT NULL,
  `os` INT UNSIGNED NOT NULL,
  `cpu` VARCHAR(45) NOT NULL,
  `ram` INT NOT NULL,
  `graphics` VARCHAR(45) NOT NULL,
  `opengl` VARCHAR(45) NOT NULL,
  `directx` VARCHAR(45) NOT NULL,
  `disk` INT NOT NULL,
  UNIQUE INDEX `idrequirements_game_UNIQUE` (`id` ASC),
  INDEX `requirements_game_os_idx` (`os` ASC),
  CONSTRAINT `requirements_game_os`
    FOREIGN KEY (`os`)
    REFERENCES `dcstore`.`os` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `requirements_game_information_software`
    FOREIGN KEY (`id`)
    REFERENCES `dcstore`.`information_game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`links_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`links_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`links` (
  `id` VARCHAR(30) NOT NULL,
  `article` VARCHAR(30) NOT NULL,
  `type` INT UNSIGNED NOT NULL,
  `description` VARCHAR(512) NULL,
  PRIMARY KEY (`id`),
  INDEX `links_links_type_idx` (`type` ASC),
  INDEX `links_article_idx` (`article` ASC),
  CONSTRAINT `links_links_type`
    FOREIGN KEY (`type`)
    REFERENCES `dcstore`.`links_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `links_article`
    FOREIGN KEY (`article`)
    REFERENCES `dcstore`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`server` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NOT NULL,
  `icon` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dcstore`.`link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dcstore`.`link` (
  `id` VARCHAR(30) NOT NULL,
  `link` VARCHAR(1024) NOT NULL,
  `password` VARCHAR(512) NULL,
  `description` VARCHAR(512) NULL,
  `server` INT UNSIGNED NOT NULL,
  INDEX `link_links_idx` (`id` ASC),
  INDEX `link_server_idx` (`server` ASC),
  CONSTRAINT `link_links`
    FOREIGN KEY (`id`)
    REFERENCES `dcstore`.`links` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `link_server`
    FOREIGN KEY (`server`)
    REFERENCES `dcstore`.`server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;